// Code generated by goagen v1.4.0, DO NOT EDIT.
//
// API "Task": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/fk2000/swagger-goa/design
// --out=$(GOPATH)/src/github.com/fk2000/swagger-goa
// --version=v1.4.0

package app

import (
	"fmt"
	"strings"
)

// TasksHref returns the resource href.
func TasksHref(taskID interface{}) string {
	paramtaskID := strings.TrimLeftFunc(fmt.Sprintf("%v", taskID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/tasks/%v", paramtaskID)
}
